services:
  - type: web
    name: storyai
    env: python
    region: oregon
    plan: free
    buildCommand: |
      pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
    startCommand: cd backend && python server.py
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: HEYGEN_API_KEY
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
