services:
  - type: web
    name: storyai
    env: python
    region: oregon
    plan: free

    # → Kjo e thotë Render-it që të hyjë në /backend
    rootDir: backend

    buildCommand: |
      pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt

    startCommand: python server.py   # s’kemi nevojë për cd sepse jemi tashmë në backend

    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: HEYGEN_API_KEY
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
